trigger:
  - main

pool:
  name: npd-portfolio
  

stages:
  - stage: DeployInfrastructure
    jobs:
      - job: Terraform
        steps:
          - checkout: self

          - task: TerraformInstaller@0
            inputs:
              terraformVersion: 'latest'

          - script: |
              cd /home/user/Terraform/
              terraform init
              terraform plan
              terraform apply -auto-approve
            displayName: "Deploy Docker Containers with Terraform"
